{% set version = '0.1.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidyplots
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidyplots_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyplots/tidyplots_{{ version }}.tar.gz
  sha256: f59c5898155b15e1e74345d1b977f560a433b1c7b5da6fb3f3434ed5bed7abdc

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-hmisc
    - r-cli
    - r-dplyr
    - r-forcats
    - r-ggbeeswarm
    - r-ggplot2
    - r-ggpubr
    - r-ggrastr
    - r-ggrepel
    - r-glue
    - r-htmltools
    - r-lifecycle
    - r-patchwork
    - r-purrr
    - r-rlang
    - r-scales
    - r-stringr
    - r-tidyr
    - r-tidyselect
  run:
    - r-base
    - r-hmisc
    - r-cli
    - r-dplyr
    - r-forcats
    - r-ggbeeswarm
    - r-ggplot2
    - r-ggpubr
    - r-ggrastr
    - r-ggrepel
    - r-glue
    - r-htmltools
    - r-lifecycle
    - r-patchwork
    - r-purrr
    - r-rlang
    - r-scales
    - r-stringr
    - r-tidyr
    - r-tidyselect

test:
  commands:
    - $R -e "library('tidyplots')"           # [not win]
    - "\"%R%\" -e \"library('tidyplots')\""  # [win]

about:
  home: https://github.com/jbengler/tidyplots, https://jbengler.github.io/tidyplots/
  license: MIT
  summary: The goal of 'tidyplots' is to streamline the creation of publication-ready plots for
    scientific papers. It allows to gradually add, remove and adjust plot components
    using a consistent and intuitive syntax.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - thewchan

# Package: tidyplots
# Title: Tidy Plots for Scientific Papers
# Version: 0.1.2
# Authors@R: person("Jan Broder", "Engler", , "broder.engler@gmail.com", role = c("aut", "cre", "cph"), comment = c(ORCID = "0000-0002-3169-2076"))
# Description: The goal of 'tidyplots' is to streamline the creation of publication-ready plots for scientific papers. It allows to gradually add, remove and adjust plot components using a consistent and intuitive syntax.
# License: MIT + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.3.2
# Imports: cli, dplyr, forcats, ggbeeswarm, ggplot2, ggpubr, ggrastr, ggrepel, glue, Hmisc, htmltools, lifecycle, patchwork, purrr, rlang, scales, stringr, tidyr, tidyselect
# Depends: R (>= 2.10)
# LazyData: true
# URL: https://github.com/jbengler/tidyplots, https://jbengler.github.io/tidyplots/
# BugReports: https://github.com/jbengler/tidyplots/issues
# Suggests: knitr, rmarkdown, testthat (>= 3.0.0), vdiffr
# VignetteBuilder: knitr
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2024-11-06 23:27:30 UTC; janbroderengler
# Author: Jan Broder Engler [aut, cre, cph] (<https://orcid.org/0000-0002-3169-2076>)
# Maintainer: Jan Broder Engler <broder.engler@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-11-08 15:00:02 UTC
